name: plant_doctor
description: Application d'analyse des maladies des plantes

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  image_picker: ^1.0.4
  camera: ^0.10.5
  geolocator: ^11.0.1
  permission_handler: ^11.0.1
  provider: ^6.1.1
  image: ^4.0.17
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true